services:
  db:
    image: postgres:16
    container_name: adapi-db
    environment:
      POSTGRES_USER: ada
      POSTGRES_PASSWORD: ada
      POSTGRES_DB: adapi
    ports:
      - "5432:5432"
    volumes:
      - ./adapi.sql:/docker-entrypoint-initdb.d/01-adapi.sql
      - adapi-data:/var/lib/postgresql/data

