### GET tous les objets
GET http://localhost:3000/api/objets

### GET objets filtrés par statut
GET http://localhost:3000/api/objets?statut=en_rayon

### GET objets filtrés par catégorie
GET http://localhost:3000/api/objets?categorie_id=1

### GET objets avec les deux filtres
GET http://localhost:3000/api/objets?statut=en_rayon&categorie_id=1

### GET un objet existant
GET http://localhost:3000/api/objets/1

### GET objet inexistant - erreur 404
GET http://localhost:3000/api/objets/999999

### GET filtre statut invalide
GET http://localhost:3000/api/objets?statut=n_importe_quoi

### GET filtre categorie invalide
GET http://localhost:3000/api/objets?categorie_id=abc



### PATCH modifier le statut d'un objet
PATCH http://localhost:3000/api/objets/163/statut
Content-Type: application/json

{
  "statut": "en_reparation"
}

### PATCH statut invalide - erreur 400
PATCH http://localhost:3000/api/objets/163/statut
Content-Type: application/json

{
  "statut": "n_importe_quoi"
}

### PATCH objet inexistant - erreur 404
PATCH http://localhost:3000/api/objets/999999/statut
Content-Type: application/json

{
  "statut": "en_rayon"
}